name: ReleaseWorkflow

on:
  push:
    branches:
      - main

jobs:
  createSentryRelease:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master

      - uses: actions/cache@v1
        with:
        path: node_modules/
        key: ${{ runner.os }}-npm-${{ hashFiles('yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-npm-

      - name: Install dependencies
        run: yarn install

      - name: Build
        run: |
          cd website
          yarn build

      - name: Create a Sentry.io release
        uses: tclindner/sentry-releases-action@v1.2.0
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
          SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
        with:
          tagName: ${{ github.sha }}
          environment: production
          sourceMapOptions: '{"include": ["./website/.next"], "ignore": ["node_modules"], "urlPrefix": "~/_next"}'
          ext: ['map']
